### ISSUE TITLE
ubunutu20.04

### ISSUE THREAD

**Issue by mlc1212** [yangliu9527/Object_SLAM#2]
When I command the following I get an error：
./Examples/Monocular/mono_kitti Vocabulary/ORBvoc.txt Examples/Monocular/KITTI00-02.yaml ~/datasets/00/
The error is as follows：
ORB Extractor Parameters: 
- Number of Features: 2000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

-------
Start processing sequence ...
Images in the sequence: 4541

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) ../modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
How should I fix it？Thanks

**Comment by yangliu9527** [comment]
This work is developed based on OpenCV3 (OpenCV2 may be also OK). So you can try to change the version of OpenCV from 4.X to 3.X.
